# Generated by Django 3.0.5 on 2020-08-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furryfur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petsitter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='petsitter',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='petsitter',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='petsitter',
            name='password',
        ),
        migrations.AddField(
            model_name='petsitter',
            name='description',
            field=models.CharField(default='', max_length=600),
            preserve_default=False,
        ),
    ]
