# Generated by Django 3.0.5 on 2020-08-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furryfur', '0002_auto_20200807_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='boarding',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='boarding_price',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='cat',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='contact_info',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='dog',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='dog_size1',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='dog_size2',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='dog_size3',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='dog_size4',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='dog_walking',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='dog_walking_price',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='doggy_day_care',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='doggy_day_care_price',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='house_sitting',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='house_sitting_price',
            field=models.CharField(max_length=2),
        ),
    ]
